### ISSUE TITLE
VSCode Rust extension does not work

### ISSUE THREAD

**Issue by xzmeng** [gitpod-io/workspace-images#832] opened 2022-05-12 13:59 UTC
### Bug description

When I open a rust project and install the official rust extension. Two error messages popped up:

1. Rustup not available. Install from https://www.rustup.rs/
2. Couldn't start client Rust Language Server

Checked up the output, it seems that rustup wrapper was invoked by dash so that a syntax error occurred.

### Steps to reproduce

1. Open any workspace with browser VSCode.
2. Install the official Rust extension.
3. Create a .rs file and open it with editor, error messages will pop up.

**Comment by xzmeng** [comment] 2022-05-12 17:54
Do we have a better way to achieve what does the `rustup wrapper` do now?
I don't know what problem it is used to solve, but it does lead to new problems:

1. I found the `rustup wrapper` always returns a 0, which is not consistent with the original `rustup`'s behavior and may break external tools that rely on its return value.
2. the `rust wrapper` will break itself when called concurrently, which did happen when I tried to work around by adding the missing shebang directive. From what I have observed, `rustup` needs to be called five times when the extension is initialized.

**Comment by jenting** [comment] 2022-05-18 01:45
@utam0k Have you encounter this?

**Comment by utam0k** [comment] 2022-05-18 02:39
@jenting No, I haven't. But I always use rust-analyzer(not rust official extend)

**Comment by utam0k** [comment] 2022-05-18 02:56
@xzmeng Hi, thanks for your report! I tried to reproduce this issue, but I couldn't. please tell me more detailed or the repository I can touch on this issue 🙏 
https://github.com/utam0k/gitpod-playground/tree/rust-ext

**Comment by jcornaz** [comment] 2022-05-19 10:40
@xzmeng which extension do you call the "official" rust extension?

Because the extension named "rust" (id: `rust-lang.rust`) is no longer the one officially recommended by the rust team and the vscode team. That one is a `legacy` one, that is about to be deprecated.

The recommended rust extension is: "rust-analyzer" (id: `matklad.rust-analyzer`). And I personnaly have no problem with that one.

Sources:
* https://code.visualstudio.com/docs/languages/rust
* https://blog.rust-lang.org/2022/02/21/rust-analyzer-joins-rust-org.html

**Comment by xzmeng** [comment] 2022-05-19 11:01
Yeah, I just started to learn rust, and after this I switched to `rust-analyzer` which doesn't seem to call rustup command and works well.
But the problems about `rustup` still exist.

**Comment by xzmeng** [comment] 2022-05-19 11:12
@utam0k I am new to rust and didn't use rust-analyzer at first. Now the problem does not bother me any more.
But the problems about `rustup` still exist. Apart from the two mentioned above, I cannot use rustup with zsh or fish. It broken itself after the first calling.

**Comment by axonasif** [comment] 2022-05-20 00:37
Now you guys can use **gitpod/workspace-rust:[2022-05-19-23-37-25](https://hub.docker.com/layers/workspace-rust/gitpod/workspace-rust/2022-05-19-23-37-25/images/sha256-11408ebf6299bdef9c38af2af15d3853c9e36628add4c964f24e025dcc15c001?context=explore)** on your `.gitpod.yml image:` or custom dockerfile as #840 was merged 🎉

**Closed by axonasif** 2022-05-20 00:37 UTC
Labels: bug, team: workspace

**Comment by utam0k** [comment] 2022-05-20 00:42
Thanks @axonasif
