### ISSUE TITLE
Consider Tools

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/workspace-images#18] opened 2018-09-03 06:44 UTC
This post by @remy contains a lot of improved variants of standard tools.
We should go through them and decide whether or not we want to install them in the default image. 

https://remysharp.com/2018/08/23/cli-improved

**Comment by jankeromnes** [comment] 2020-04-27 15:06
Duplicate of https://github.com/gitpod-io/workspace-images/issues/76

**Closed by jankeromnes** 2020-04-27 15:06 UTC
