### ISSUE TITLE
FSharp interactive not properly installed

### ISSUE THREAD

**Issue by simonelnahas** [gitpod-io/workspace-images#193] opened 2020-04-02 13:42 UTC
Running the command gives an error in gitpod, but it works when running locally.

```
gitpod /workspace/FsLexYaccServerTemplate $ fsharpi analyser/program.fsx 


error FS0193: Specified method is not supported.
```
The error should be replicable by opening this [commit](https://github.com/simonelnahas/FsLexYaccServerTemplate/tree/add50d3c4c81f8e7ffd7fb79d07d199733c3a046) on GitPod.

**Comment by simonelnahas** [comment] 2020-04-02 13:49
The `$ fsharpi ` command works, but this issue suggests there is something wrong with the installation:
https://github.com/fsharp/fsharp/issues/740

**Comment by simonelnahas** [comment] 2020-04-02 14:51
may do something similar to this: https://github.com/nblockchain/geewallet/commit/0326aa3564edd4c5a3d14ae6c09c0dbde3253f48

**Comment by svenefftinge** [comment] 2020-04-07 07:33
Hey Sean (@JesterOrNot), could you have a look into this? It seems like the mono version of `fsharpi` doesn't work with our version of ubuntu (see the issue referenced above). We probably should use an image that is not based on our workspace-full for this.

**Comment by JesterOrNot** [comment] 2020-04-07 21:04
Hey, sorry this hasn't worked for you :( I will continue to look into this. In the meantime I have fixed some errors in your .gitpod.yml.  https://github.com/simonelnahas/FsLexYaccServerTemplate/pull/2

**Comment by JesterOrNot** [comment] 2020-04-09 01:50
Hello Almost done I have it working now with the test branch!

![image](https://user-images.githubusercontent.com/50386709/78849410-0744c400-79da-11ea-82b2-a65d06deabb8.png)

Now all that should be left is optimization!

**Comment by simonelnahas** [comment] 2020-04-09 12:05
Cool i'm looking forward to it! :)

**Comment by jankeromnes** [comment] 2020-05-22 18:23
@JesterOrNot What is the status of this issue? Are there still some changes required to Gitpod's `dotnet` Dockerfiles, or is FSharp interactive now properly installed?

**Comment by sr229** [comment] 2021-04-20 12:21
Just a note, this is now obsolete as dotnet tools now handle F# within .NET 5.0. run your F# tools with `dotnet fsi` instead.

@jankeromnes I suggest closing this now since this is more of a fixed issue now :D

**Comment by princerachit** [comment] 2022-02-28 07:05
Closing this PR as the issue is fixed in recent versions of dotnet

**Closed by princerachit** 2022-02-28 07:05 UTC
