### ISSUE TITLE
Update ca-certificates Package in workspace-full Image

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/workspace-images#599] opened 2021-12-22 14:52 UTC
This is similar to #528 where the `ca-certificates` package needs to be updated in order to do things like Git pulling or pushing from/to a self-hosted GitHub Enterprise, GitLab, etc instance that is using a Let's Encrypt certificate. From the current `workspace-full` image:

```
$ sudo apt list --installed |grep ca-certificates
ca-certificates/now 20210119~20.04.1 all [installed,upgradable to: 20210119~20.04.2]
```

This package should be updated to `20210119~20.04.2`. Alternatively I believe the `workspace-full` image can just be rebuilt as if I recall it runs `apt -y update && apt -y upgrade`. See [my comment here](https://github.com/gitpod-io/gitpod/issues/5984#issuecomment-985682897) as it looks like a rebuild of the `workspace-full` image will update a bunch of packages, not just the `ca-certificates` one.

**Comment by gtsiolis** [comment] 2021-12-27 12:25
Looping in @gitpod-io/engineering-meta in case this is something we could easily resolve.

See relevant issue in https://github.com/gitpod-io/gitpod/issues/5984.

Cc @kylos101 because [relevant AOR](https://www.notion.so/gitpod/Maintain-Workspace-Images-bd619236888845379557ef77bedbee84) (internal)

**Comment by atduarte** [comment] 2022-01-31 09:51
This looks like a duplicate of https://github.com/gitpod-io/gitpod/issues/5984. Should we close it @kylos101?

**Closed** 2022-02-01 06:29 UTC
Labels: team: workspace
